export enum NoteType {
  LECTURE_NOTES = 'LECTURE_NOTES',
  SUMMARY = 'SUMMARY',
  REVISION = 'REVISION',
  PAST_EXAM = 'PAST_EXAM',
  EXERCISES = 'EXERCISES',
}

export enum NoteStatus {
  DRAFT = 'DRAFT',
  CONVERTED = 'CONVERTED',
  PENDING_REVIEW = 'PENDING_REVIEW',
  PUBLISHED = 'PUBLISHED',
  REJECTED = 'REJECTED',
  ARCHIVED = 'ARCHIVED',
}
